### ISSUE TITLE
Add support for errors-in-variables models

### ISSUE THREAD

**Issue by palday** [paul-buerkner/brms#114]
How difficult would it be to add support for errors-in-variables models such as those discussed recently on the [Gelman blog](http://andrewgelman.com/2016/09/04/29847/), especially in reference to the new [Westfall & Yarkoni paper](http://dx.doi.org/10.1371/journal.pone.0152719).

From Chapter 11.1 of the Stan manual, you would need to transform this model:

``` stan
data {
  int<lower=0> N;      // number of cases
  real x[N];           // predictor (covariate)
  real y[N];           // outcome (variate)
}
parameters {
  real alpha;          // intercept
  real beta;           // slope
  real<lower=0> sigma; // outcome noise
}
model {
  y ~ normal(alpha + beta * x, sigma); // regression model
  alpha ~ normal(0, 10);               // prior
  beta ~ normal(0, 10);                // prior
  sigma ~ cauchy(0, 5);                // prior
}
```

into this model (assuming constant/homogeneous and known noise):

``` stan
data {
  int<lower=0> N;      // number of cases
  real x_meas[N];      // predictor (covariate) as measured
  real<lower=0> tau;   // measurement noise
  real y[N];           // outcome (variate)
}
parameters {
  real x[N];           // unknown true value
  real mu_x;           // prior location
  real sigma_x;        // prior scale
  real alpha;          // intercept
  real beta;           // slope
  real<lower=0> sigma; // outcome noise
}
model {
  x ~ normal(mu_x, sigma_x);            // prior on x
  x_meas ~ normal(x, tau);              // measurement model
  y ~ normal(alpha + beta * x, sigma);  // regression model
  alpha ~ normal(0, 10);                // prior
  beta ~ normal(0, 10);                 // prior
  sigma ~ cauchy(0, 5);                 // prior
  // do we need priors on mu_x and sigma_x? 
}
```

It seems that you would need to add 2 more arguments to `brm()`: 
1. a list of variables for which the intermediate parameter needs to be constructed (i.e. variables measured with error) 
2. a list of error distributions for those variables, with normal being the default (but what would be a good default setting for the scale paramter here?)

As well as potentially:
3. Priors on constructed intermediates parameters
4. A method to estimate the scale parameter for the measurement-error distribution from the data

Adding the actual transformation from the first model to the second seems straightforward enough, but incorporating all the extra arguments and options might be far more challenging.

(I'm willing to try to help, as we all have other day jobs here, so I'm trying to understand what exactly needs to be done.)

**Comment by paul-buerkner** [comment]
This seems to be an interesting idea! I already have an idea to handle the additional arguments. One could add a special function (let's call it `me` for measurement error for now) that would go into the formula argument, for instance `y ~ 1 + z + me(x)`. This would specify `x` as being measured with error. I am doing the same thing with category specific and monotonic effects already, so the code structure ist mostly there.

**Comment by palday** [comment]
Yeah, a special function would make things much more readable and the model structure more obvious than even more keyword arguments.

**Comment by paul-buerkner** [comment]
Using functions inside the formula also makes things easier from the developing perspective. Regarding the error distributions, I am not sure if I want to allow other than distributions than the normal distribution, simply because it adds much complexity in both the Stan code generation and all S3 methods dealing with predictions.

**Comment by palday** [comment]
I suppose anything beyond normal distribution is getting to the point where you should be hand-coding your Stan model anyway. But maybe support for a t-distribution as well as a way to handle small sample sizes / allow for fatter tails? Of course, that adds complexity in estimating the degrees of freedom (unless you just take an easy empirical df equal to the number of measurements minus 1) and even a normal distribution for measurement errors is already a big boost compared to the current practice in many fields (ignoring the problem).

**Comment by waynefoltaERI** [comment]
Very timely. We have technical talks in our company every Friday and I've proposed the topic of Errors In Variables for one of our upcoming talks. To be honest, I don't know much more about the topic than a Wikipedia paragraph, but it's definitely something that often gets overlooked and making it easier to handle without resorting to a different function is a great idea.

**Comment by jebyrnes** [comment]
Just wanted to throw in a thanks for thinking about this, and I'm eagerly awaiting the update. I've been dealing with EiV by using rethinking (which is awesome) instead of BRMS, but I find that, even for the same models, the formulation you've been putting together in BRMS converges **much** faster. So, I and my colleagues (particularly those that do Structural Equation Modeling) are pretty damned excited for this feature in BRMS.  Happy to take anything for a test-drive for you - e.g., test the me() results from brms with some of the rethinking examples that I have put together already.

**Comment by paul-buerkner** [comment]
Can you give me one or two examples of what kind of models you specify with rethinking so that I can get a sense of how complicated your EiV models are?

**Comment by jebyrnes** [comment]
Sure! Here's given that we'd be using `me()` to implement measurement error, I'm thinking of something like

```
my_mod <- brm(response | se(response_error) ~ me(predictor_1)*me(predictor_2)*predictor_3, 
data=my_data)
```

(I've got two variables, they interact, and there's a third - and actually fourth...and maybe fifth, depending on WAIC - predictor with no measurement error that might interact with them.)

If that's not possible, me.

Happy to post the rethinking one-variable EiV model if it's useful to you. 

This also might be an insane model. Or might not.

**Comment by paul-buerkner** [comment]
Hey, thanks for the example. Implementing a special function `me` in **brms** to handle measurement error variables should not be too difficult since the internal structure is already there from other such functions.

Modeling interactions between `me` and other variables is not so straight forward anymore. The reason is that **brms** works with design matrices for population-level ("fixed") effects, but the `me` variables would not fit in this framework. I am thus not yet sure how to tackle these interactions without completely redoing the formula parsing.

In a first step, I could implement main effects of `me` variables and then allow interactions later on.

I would be grateful for an example implemented in rethinking.

**Comment by jebyrnes** [comment]
Sure - here are three rethinking models - https://gist.github.com/jebyrnes/32c8a83ef225b4e69e073413abdc0997

The first incorporates measurement error in the response and one predictor. The second, both predictors, although they combine additively, and the third model allows for an interaction. 

To see the STAN code behind any individual model, check the model slot after fitting it - e.g. `cat(fit_all_int@model)` (or don't fit it with `sample=FALSE`).

**Comment by paul-buerkner** [comment]
Thanks for the examples. I will start implementing measurement error in single predictors and then see how we can expand that to predictor interactions and to the response variable.

**Comment by jebyrnes** [comment]
You're amazing. Happy to do any testing you need.

**Comment by jebyrnes** [comment]
And you already have error in the response with `se()` - that's taken care of!

**Comment by paul-buerkner** [comment]
I Just pushed some commits to github implementing a preliminary version of error-in-variables models. You can now write something like

```R
brm(response | se(response_error) ~ me(predictor_1, noise_1)*me(predictor_2, noise_2)*predictor_3, 
data=my_data)
```

and it will (hopefully) work. Noisy variables are also allowed in group-level terms ('random effects').
Some stuff is still missing:

- [ ] full support in S3 methods such as `predict`
- [ ] unit tests
- [ ] documentation

In addition to being grateful for anyone who wants to test this feature, I have some questions I want to disuss.

1. Should the noise of each variable be computed from the data? If yes, how?
2. Should we save the noise-free variables by default (this will lead to huge R objects)?

**Comment by jebyrnes** [comment]
Fantastic - thanks! Anything we can do to help with `predict` or other methods?

For #1, what do you mean by the noise of each variable being computed from the data? Not sure, given that the sd (perhaps should specify that it's SD and not variance?) of each variable is being supplied.

 As for #2 - I think...no? Most folk aren't interested in the noise free variables in such a case (well, they might be interested in noise-free response variables, but you can get that from your posterior prediction distribution anyway). I think the default no behavior should be fine.

**Comment by jebyrnes** [comment]
Hrm - I also got very different results between brms and rethinking. To remind you, the model from https://gist.github.com/jebyrnes/32c8a83ef225b4e69e073413abdc0997 is:
```
  #likelihood
  div_est ~ dnorm(mu, sigma),
  
  #model
  mu <- a + bA*age_est[i] + bR*mar_est[i] + bI*age_est[i]*mar_est[i],
  
  #error in both response and predictor
  div_obs ~ dnorm(div_est, div_sd),

  age_obs ~ dnorm(age_est, age_sd),
  mar_obs ~ dnorm(mar_est, mar_sd)
```

And in brms, I implemented this with

```
mod_int_brm <- brm(div_obs | se(div_sd) ~ me(age_obs, age_sd)*me(mar_obs, mar_sd),
                   data=d, iter=5000, warmup=1000, chains=3)
```

which produced the following:

```
> precis(fit_all_int, prob = 0.95)
       Mean StdDev lower 0.95 upper 0.95 n_eff Rhat
a      8.94   9.45      -9.24      28.09  4207 1.00
bA    -0.04   0.36      -0.77       0.67  3952 1.00
bR     0.99   0.56      -0.10       2.11  1663 1.00
bI    -0.04   0.02      -0.08       0.01  1541 1.00
sigma  0.81   0.27       0.29       1.33   444 1.01

> summary(mod_int_brm)$fixed
                                   Estimate   Est.Error    l-95% CI   u-95% CI Eff.Sample     Rhat
Intercept                       52.22183908 20.04809911 11.77276147 91.8662765   291.9718 1.009925
meage_obsage_sd                 -1.65720723  0.76675571 -3.18118693 -0.1047509   288.0985 1.009494
memar_obsmar_sd                 -0.75894834  0.97713905 -2.66954807  1.3101108   292.4485 1.010063
meage_obsage_sd:memar_obsmar_sd  0.02974383  0.03795441 -0.04991679  0.1046896   292.5470 1.009514
```

Hrm....

**Comment by paul-buerkner** [comment]
@jebyrnes There are two issues here: 

1. You forgot to include `sigma` in the **brms** model. The `se` argument was primarily written for meta-analysis so it replaces `sigma` by default. You can add it again using a random effect with as many levels as observations in the data:

```R
d$obs <- 1:nrow(d)
mod_int_brm <- brm(div_obs | se(div_sd) ~ me(age_obs, age_sd)*me(mar_obs, mar_sd) + (1|obs),
                   data=d, iter=5000, warmup=1000, chains=3)
```

This is a bit inefficient with respect to computation and I am thinking of implementing a way to include sigma naturally in addition to known noise passed via `se`.

2. The priors in the **rethinking** model are very informative. Set their sd / scale to 100 or so and you will see the results being very similar. 

My point (1): You are right and I should make clear that the noise is SD not VAR.

My point (2): Don't we need those samples for predictions? Or can we just "sample" from `normal(x_noise, noise)` in the predictions again? I am not used to work with these models...

**Comment by paul-buerkner** [comment]
With the latest dev version, you can now write

```R
mod_int_brm <- brm(div_obs | se(div_sd, sigma = TRUE) ~ me(age_obs, age_sd)*me(mar_obs, mar_sd),
                   data=d, iter=5000, warmup=1000, chains=3)
```

to model `sigma` in addition to the known standard errors.

**Comment by paul-buerkner** [comment]
Error-in-variables models are now fully implemented including support of S3 methods, unit tests and documentation. I am grateful for anyone willing to test the new features and provide feedback on whatever should be improved.

**Comment by mattnw** [comment]
I think the "me" feature is a great addition - I was very excited to see this in the manual. I'm wondering, would it be possible to put a prior on the measurement error standard deviation rather than selecting a fixed "known" value?

**Comment by paul-buerkner** [comment]
I am not sure if this is possible / reasonable. As far as my understanding goes, these models are desigend so that one passes a variable containing the "known" standard deviations (it is not a single value but a variable in the data), but I am admitedly not an expert so someone else might one to step in.

How would a model look like using a prior on the SDs in your opinion?

**Comment by mattnw** [comment]
Hi Paul, I was thinking along the lines of the model below, where instead of assuming we know that the measurement error of X is a fixed value, we place a prior on this measurement error. Here the prior is half-Cauchy(0, 1).

```stan
data {
int<lower=0> N;      // number of cases
vector[N] x_meas;           // observed predictor with error
vector[N] y;           // outcome (variate)

}
parameters {
vector[N] x;           // unknown true value of X
real mu_x;          // prior location of x
real sigma_x;          //prior scale of x
real alpha;          // intercept
real beta;           // slope
real<lower=0> sigma; // outcome noise
real<lower=0> tau;   // measurement noise
}
model {
x ~ normal(mu_x, sigma_x);  //prior on x
tau ~ cauchy(0, 1); // prior on SD of measurement noise
x_meas ~ normal(x, tau);    // measurement model
alpha ~ normal(0, 1000);               // prior
beta ~ normal(0, 1);                // prior
sigma ~ cauchy(0, 5);       //prior
y ~ normal(alpha + beta * x, sigma);
}
```

That said, on reflection I'm not sure if this is appropriate to build into brms. Placing a prior on the measurement error standard deviation tau seems intuitively more appropriate than fixing it to a particular value. But the pitfall here is that the posterior distribution of tau is determined completely by its prior (it's not estimable from the data). So if you set that prior carelessly the results get really weird - including for the example prior I've given here, which places non-trivial probability on an extremely large quantity of measurement error). So maybe don't worry about this for now :)

**Comment by ASKurz** [comment]
Hey Paul, I’ve been replicating jebrynes’ comparison--from back in Nov 30--with the way brms and rethinking behave when estimating model m.14.2 from McElreath’s text. I see what you mean about how strong McElreath’s prior was, particularly the one on the intercept. That leaves me wondering, though. Do you have a sense of why brms was less sensitive than rethinking to the dnorm(0, 10) prior?

**Comment by paul-buerkner** [comment]
The reason is that brms uses a different paramterization internally that contains a temporary intercept to speed up sampling (the actual intercept is computed later on). The intercept prior is applied on this temporary intercept as explained in the doc of `set_prior`, which is the reason brms and rethinking react differntly to the prior.

**Comment by ASKurz** [comment]
Huh. The rabbit hole deepens. Thanks Paul.

**Comment by waynefoltaERI** [comment]
@paul-buerkner I've had a question about this temporary intercept that I hadn't asked, but perhaps you can clarify. I think you center the data and it's the intercept for the centered data? Is that correct?

So I'm thinking that if I have reason to believe that the actual intercept will be positive -- say 10 +/- some SD -- and I wanted to set up a reasonably strong prior, I would not use a normal with mean 10, but would instead use a normal with mean 0? (Same SD in either case.) Or am I really confused?

So far I've used fairly broad priors in this case, since I was really only trying to tame sampling a bit rather than make a strong statement, but I always felt like I was not really doing the right thing.

**Comment by paul-buerkner** [comment]
The situation is actually a bit more complicated. The formula for the original intercept is
`b_intercept = temp_intercept - dot_product(means_X, b)`, where `means_X` is the vector of means of the predictor variables and `b` is the vector of regression coefficients (fixed effects). That is, when transforming a prior on the intercept to an "equivalent" prior on the temporary intercept, you have to take the means of the predictors and well as the priors on the other coefficients into account. Admittedly, this is rather hard and I wouldn't recommend doing it.

However, it wouldn't be brms if there was no work aroung, right? ;-) You can just add `0 + intercept` to your formula and have a normal behaving intercept. You sacrifice the efficiency improvement, but can add priors directly to the intercept via `set_prior(., coef = "intercept")`.

**Comment by jgabry** [comment]
Another argument for doing the intercept this way (beyond the potential efficiency gains) is that it's often (though not always) easier to reason about the intercept when X is centered.

**Comment by ASKurz** [comment]
And there it is. After using `0 + intercept` in my formula, the results now mimic those in McElreath's text:

Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
intercept    21.35      6.51     8.30    34.11       1913    1
R             0.13      0.07    -0.02     0.27       2076    1
A            -0.55      0.21    -0.96    -0.12       2024    1

Family Specific Parameters: 
      Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sigma     1.12      0.21     0.76     1.57       3009    1

**Comment by waynefoltaERI** [comment]
Thanks! If I read your formula correctly, if the predictor variables are all centered, does the dot product end up zero and hence the temp intercept is the same as the real intercept? I've not generally centered my predictors because I'm lazy, but I really should do so in general -- for better interpretability, etc -- and if it allows a more efficient algorithm while still allowing me to specify an intercept prior in a principled manner, that'd be a win-win approach.

Not sure how random effects affect things, since it appears that only the fixed effects enter into the dot product.

**Comment by paul-buerkner** [comment]
> If I read your formula correctly, if the predictor variables are all centered, does the dot product end up zero and hence the temp intercept is the same as the real intercept?

Exactly! 

The random effects don't matter for the recentering.

**Comment by waynefoltaERI** [comment]
If I could suggest that this could be expanded a bit and added as a tip in the documentation on `brms_formula`. (Maybe it's in there and I missed it.) Maybe something like:

>  ... The bias is corrected after fitting the model, but be aware that you are effectively defining a prior on the temporary intercept of the centered design matrix not on the real intercept.
>
> In practice, this means that there are three strategies for correctly specifying the prior for the population intercept: 1) use a very vague prior, including the default uniform prior; 2) center your population (fixed-effect) variables, in which case the temporary and actual intercept will be the same; or 3) use the special function `intercept` in your formula and eliminate R's default intercept `0 + intercept`, then specify the prior for the actual intercept. The third option will be less efficient sampling-wise than the other two, though this may or may not make a noticeable difference in your particular case.
> 
> If you do not do one of these three things and you specify an informative prior for the intercept, you risk having your misplaced prior affect the actual intercept in confusing or erroneous ways. You do not have to center group (random-effect) variables, but as always centering your variables can make your model more interpretable.

**Comment by jgabry** [comment]
Clarifying further in the doc seems like a good idea, but I think referring
to it as a "temporary" intercept is technically correct but has the
unintended effect of discouraging taking it seriously. I think in general
it would be good to encouraged specifying a prior for the intercept
interpreted as expected y at x=xbar rather than at the often meaningless
(unless already centered) value x=0. There are certainly exceptions, but
it's not only efficiency you lose but also often interpretability.

Of course in the case where you already have an informative prior for the
intercept then that advice for tranforming to what brms actually needs is
great.

**Comment by rborder** [comment]
Have you considered adding support for misclassification of binary/polychotomous variables? This would be considerably more work as it requires formulating a mixture over marginal pmfs at each value of the (latent) discrete variable. But there are vary few options for these kinds of models currently--only `mcsimex` in the `simex` package and coding by hand in Stan or JAGS as far as I know.

**Comment by paul-buerkner** [comment]
I haven't thought about it but it seems interesting. Would you mind opening a new issue to discuss your ideas?
