### ISSUE TITLE
displaying models fitted pre 2.16 in brms 2.16 - variables missing in the draws object

### ISSUE THREAD

**Issue by fusaroli** [paul-buerkner/brms#1218]
After upgrading to brms 2.16, when trying to open saved models fitted with previous versions (e.g. 2.15), either by calling model or summary(model), i get "Error: The following variables are missing in the draws object: " followed by a long list of model parameters (e.g. Cor_1_1[1,1]).

The models look otherwise fine in the environment pane in rstudio.

Is there a basic conversion to be done to the models to comply with the new "draws" hegemony, which I have missed?

**Comment by paul-buerkner** [comment]
This is not great as I assume a lot of people will have this problem. Can you send me such a model than complains this way?

**Comment by fusaroli** [comment]
sorry, was away from the computer. I seem to only have relatively complex models at hand, but here it's a gaussian one, so the issue shouldn't just be e.g. in mixture models: 
- https://www.dropbox.com/s/iawss4unif9094b/ChildMLUPred0_m.rds?dl=0

**Comment by paul-buerkner** [comment]
Thank you! The problem is actually caused by (what is think might by a bug in) `rstan::read_stan_csv` when reading in CSVs created by cmdstanr. As such this will only happen for models fitted with the cmdstanr backend. The reason this became apparent only now is the use of the posterior package which is more strict about variable names. This is automatically fixed for newly fitted models with brms 2.16.0 and I just pushed a fix to github that does the same for old models.

@jgabry, @bgoodri, @hsbadr: It seems as if `rstan::read_stan_csv` accidently renames parameter names in `stanfit@sim$samples` causing, for example, dimension brackets etc., to be replaced by a `.` as a result of an implicit call to `make.names` I assume. 

I am now working around this issue in brms via the following helper function:

```R
# repairs parameter names of stanfit objects as rstan::read_stan_csv 
# seems to accidentally rename dimension suffixes
repair_stanfit_names <- function(x) {
  stopifnot(is.stanfit(x))
  for (i in seq_along(x@sim$samples)) {
    names(x@sim$samples[[i]]) <- x@sim$fnames_oi
  }
  x
}
```

**Comment by fusaroli** [comment]
awesome, thanks. this now works on a bunch of different models, but there's still at least one issue.
If I try to load zero inflated models, I get 

"Error: Duplicate variable names are not allowed in draws objects.
The following variable names are duplicates:
{'prior_sd_ChildID'}"

This happens for a range of zi models (gaussian, poisson and lognormal),

Simplest example here: https://www.dropbox.com/s/f7un4askscu27zu/ChildMLUPred0_zi_m.rds?dl=0

**Comment by paul-buerkner** [comment]
Strange. I don't understand why they are duplicated in the first place. Does the same thing happen in a newly fitted model?

**Comment by paul-buerkner** [comment]
Ok. I see why it happens. Need to think of a solution.

**Comment by fusaroli** [comment]
yes, it happens in newly fitted models on 2.16 as well

**Comment by paul-buerkner** [comment]
This should now be fixed as well. It was a much rarer issue that will likely only occur in certain cases when `sample_prior = "yes"`.

**Comment by fusaroli** [comment]
confirmed. no error anymore on a range of zi models.

**Comment by Scott-Coggeshall** [comment]
I'm running into this issue as well when fitting categorical models with group-level terms when `sample_prior` is set to `"yes"`

Example:

```
library(brms) # version 2.16.2

n <- 200

# simulate categorical outcome variable and site variable
y <- sample(c("a", "b", "c", "d"), replace = TRUE)

site <- sample(c('site1', 'site2', 'site3', 'site4'), n, replace = TRUE)

dat <- data.frame(y = y, site = site)


# no sampling from prior
cat_model <- brm(y ~ (1 | site), family = categorical(), data = dat)

# sampling from prior
cat_model_withprior <- brm(y ~ (1 | site), family = categorical(), data = dat, sample_prior = "yes")
```

Calling `summary` on the model with no prior sampling works:

```
> summary(cat_model)
 Family: categorical 
  Links: mub = logit; muc = logit 
Formula: y ~ (1 | site) 
   Data: dat (Number of observations: 200) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Group-Level Effects: 
~site (Number of levels: 4) 
                  Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(mub_Intercept)     0.29      0.31     0.01     1.15 1.00     1401     1926
sd(muc_Intercept)     0.32      0.38     0.01     1.32 1.00     1074      891

Population-Level Effects: 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
mub_Intercept    -0.70      0.25    -1.22    -0.22 1.00     1824     1500
muc_Intercept    -0.68      0.28    -1.22    -0.06 1.01     1072      548

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).
```

But `summary` on the model with sampling from the prior throws an error:

```
> summary(cat_model_withprior)
Error: Duplicate variable names are not allowed in draws objects.
The following variable names are duplicates:
{'prior_sd_site'}

```

Running a categorical model with sampling from the prior works fine if no group-level terms are specified.

**Comment by paul-buerkner** [comment]
did you try 2.16.1 already? I hope to have fixed that issue there.

Scott-Coggeshall ***@***.***> schrieb am Sa., 4. Sept. 2021,
03:46:

**Comment by Scott-Coggeshall** [comment]
I re-ran the code under version 2.16.1 and had the same issues. In case it helps, here is the output from `prior_summary`

```

> prior_summary(cat_model_withprior)
                prior     class      coef group resp dpar nlpar bound       source
 student_t(3, 0, 2.5) Intercept                       mub                  default
 student_t(3, 0, 2.5) Intercept                       muc                  default
 student_t(3, 0, 2.5) Intercept                       mud                  default
 student_t(3, 0, 2.5)        sd                       mub                  default
 student_t(3, 0, 2.5)        sd                       muc                  default
 student_t(3, 0, 2.5)        sd                       mud                  default
 student_t(3, 0, 2.5)        sd            site       mub             (vectorized)
 student_t(3, 0, 2.5)        sd Intercept  site       mub             (vectorized)
 student_t(3, 0, 2.5)        sd            site       muc             (vectorized)
 student_t(3, 0, 2.5)        sd Intercept  site       muc             (vectorized)
 student_t(3, 0, 2.5)        sd            site       mud             (vectorized)
 student_t(3, 0, 2.5)        sd Intercept  site       mud             (vectorized)

```

**Comment by paul-buerkner** [comment]
Thank you. Will check what is going wrong in the next couple of days.

**Comment by paul-buerkner** [comment]
I think I just fixed it. Can you double check this is indeed the case?

**Comment by Scott-Coggeshall** [comment]
Yes, re-installed and it's now working. Thanks so much for your quick response and for the amazing `brms` package!

**Comment by grossbach** [comment]
Version 2.16.1 still throws this error in multivariate models where the names of the response variables have underscores AND random effects are estimated AND samples from the prior are drawn, e.g.
`m1_form <- bf(mvbind(resp_A, resp_B) ~ val1 +
                (1 | id)) +
  set_rescor(FALSE)
m1 <- brm(m1_form, 
          sample_prior = TRUE,
          prior = m1_prior,
          data = dat.df)`
This seems like an even rarer use case than the OP's problem but still wanted to point this out for people who have said problem.

**Comment by grossbach** [comment]
No wait, it still throws the error even if response vars have no underscores in their names (I have no idea what I did the other day that made the error disappear). Here is a reproducible example:

     n_subjects <- 200
     n_measurements <- 2
     dat.df <- tibble(id = rep(1:n_subjects,
                               times = n_measurements),
                      val = c(rnorm(n_subjects, 0, 1),
                              rnorm(n_subjects, 1.5, 1)),
                      respA = val^2 + rnorm(200, 0.5, 1),
                      respB = val + rnorm(200, 0.8, 2))
     (m_form <- m1_form <- bf(mvbind(respA, respB) ~ val +
                                (1 | id)) +
         set_rescor(FALSE))
     (m_prior <- c(
       set_prior("normal(0, 1)",
                 class = "sd",
                 resp = "respA"),
       set_prior("normal(0, 0.5)",
                 class = "sd",
                 resp = "respB"),
       set_prior("normal(0, 1)",
                 class = "b",
                 resp = "respA"),
       set_prior("normal(0, 1)",
                 class = "b",
                             resp = "respB")
       ))
     m1 <- brm(m1_form,
               prior = m_prior,
               sample_prior = TRUE,
               data = dat.df)

Calling `summary(m1)` throws the error:

Fehler: Duplicate variable names are not allowed in draws objects.
The following variable names are duplicates:
{'prior_sd_id'}

This is on R 4.1.2, brms 2.16.1 and Debian 10.1 (buster).

**Comment by paul-buerkner** [comment]
Can you check whether the problem remains in the current github version of brms?

**Comment by grossbach** [comment]
The problem has gone in the github version. Thank you very much for the swift response and the fix!
