### ISSUE TITLE
`update()`: Arguments (from `...`?) not passed to `brm()`

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1373]
It seems like `update.brmsfit()` does not pass all arguments from the original `brm()` call to the updated `brm()` call (I guess arguments from the ellipsis `...` are missing). For example: argument `init_r` in case of the rstan backend:
```r
library(brms)
options(mc.cores = parallel::detectCores(logical = FALSE))
fit_rstan <- brm(rate ~ conc + state,
                 data = Puromycin,
                 refresh = 0,
                 seed = 11403,
                 init_r = 1)
debug(brm)
upd_rstan <- update(fit_rstan,
                    formula. = rate ~ conc,
                    newdata = Puromycin,
                    refresh = 0,
                    seed = 5933)
```
Debugging `brm()` in that `update()` call up to (including) lines https://github.com/paul-buerkner/brms/blob/039d1f2f487cb6c1d9c0c080200a651ce1f8eb68/R/brm.R#L580-L583 shows that `fit_args$init_r` does not exist (only `fit_args$init`, but that is `NULL`). Specifying `init_r = 1` in the `update()` call fixes this, but it would be great not having to specify it.

Another example: arguments `init` and `adapt_delta` in case of the cmdstanr backend:
```r
library(brms)
options(mc.cores = parallel::detectCores(logical = FALSE))
fit_cmdstanr <- brm(rate ~ conc + state,
                    data = Puromycin,
                    refresh = 0,
                    seed = 11403,
                    backend = "cmdstanr",
                    adapt_delta = 0.9,
                    init = 1)
debug(brm)
upd_cmdstanr <- update(fit_cmdstanr,
                       formula. = rate ~ conc,
                       newdata = Puromycin,
                       refresh = 0,
                       seed = 5933)
```
Debugging `brm()` in that `update()` call up to (including) lines https://github.com/paul-buerkner/brms/blob/039d1f2f487cb6c1d9c0c080200a651ce1f8eb68/R/brm.R#L580-L583 shows that `fit_args$adapt_delta` does not exist and `fit_args$init` is `NULL` instead of `1`. Again, specifying `adapt_delta = 0.9` and `init = 1` in the `update()` call fixes this, but it would be great not having to specify it.

I tried both examples with branch `master` (commit https://github.com/paul-buerkner/brms/commit/039d1f2f487cb6c1d9c0c080200a651ce1f8eb68).

In #889, it sounds like this is intentioned behavior, but at that time, only arguments like `open_progress` and `refresh` were discussed (which only affect how the fitting process is displayed, not the details of the fitting process itself), whereas the arguments in the examples above do affect the fitting process, similarly to the `control` argument in #326.

**Comment by paul-buerkner** [comment]
Thanks. I will take a look!

**Comment by paul-buerkner** [comment]
Fixed.

**Comment by fweber144** [comment]
Thanks! The rstan example indeed seems to be working now. The cmdstanr example only seems to be working with respect to `fit_args$adapt_delta` (which is 0.9 now, as desired). I still get `NULL` (not `1`) for `fit_args$init` in the cmdstanr example. Or am I using `init` incorrectly?

**Comment by paul-buerkner** [comment]
argument `init` or `init_r`?

**Comment by fweber144** [comment]
I have only used `init` for cmdstanr, because `init_r` is for rstan only, right? Anyway, `fit_args$init` and `fit_args$init_r` are both `NULL`.

**Comment by paul-buerkner** [comment]
Ah yes, I see. Init should now work as well.

**Comment by fweber144** [comment]
Yes, thanks!
