### ISSUE TITLE
Marginal effects in brms for me models

### ISSUE THREAD

**Issue by hlluik** [paul-buerkner/brms#572]
Hello!

 I opened a problem yesterday, however, I was not quick enough to provide example dataset. So the problem still remains- when running a model with multiple me predictors, the problem with marginal effects remain, giving error that names' attribute [2] must be the same length as the vector [1]. So I am not sure am I doing myself something wrong or is there a some bug as the summary gives no warnings.

Simulation sample
y <- c(1,0,0,1,1,0,0,0,1,1,1,0,0,0)
x <- c(0,1,0,1,0,0,1,0,1,1,1,0,0,0)
x2 <- c(0,5,4,10,9,0,7,0,12,11,5,0,8,8)

testset <- as.data.frame(cbind(x2, x, y))
View(testset)

library(brms)

formula <- bf(y ~ me(x, 0.2) + me(x2, 0.8))+ set_mecor(FALSE)

brmtest <- brm(formula, data=testset, family=bernoulli(link="logit"), save_mevars = TRUE)

summary(brmtest)
marginal_effects(brmtest)

Thanks,
H

**Comment by paul-buerkner** [comment]
Thanks for providing a reproducible example. I fixed the problem already and thus closed the initial issue. If you install the github version of brms via

```R
if (!requireNamespace("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms")
```

the problem should go away. At least on my machine, your example runs without problems now.

P.S. You can still post in closed issues.

**Comment by hlluik** [comment]
Ahhaa, good note. I ran this code yesterday, however for me it did not solve the problem. Now re-running this, it produces following error:
package ‘backports’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘backports’

The downloaded binary packages are in
	C:\Users\Hl\AppData\Local\Temp\Rtmp0kr5sp\downloaded_packages
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Hl/AppData/Local/Temp/Rtmp0kr5sp/devtools345c8c47f8e/paul-buerkner-brms-8013064"  \
  --library="C:/Users/Hl/Documents/R/win-library/3.4" --install-tests 

ERROR: dependency 'backports' is not available for package 'brms'
* removing 'C:/Users/Hl/Documents/R/win-library/3.4/brms'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by paul-buerkner** [comment]
Go to C:/Users/Hl/Documents/R/win-library/3.4/brms and remove the "backports" folder manually.

Further, I would recommend updating R to version 3.5.1 as you currently use 3.4.x

**Comment by hlluik** [comment]
Works like perfect, thank you! 👍
